export const MILLI_SECOND = 1000;

export const SUBSCRIPTION_STATUS = {
  EXPIRED: "EXPIRED",
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  APPROVED: "APPROVED",
  APPROVAL_PEDING: "APPROVAL_PEDING",
  CANCELLED: "CANCELLED",
};
